version: "3.7"
services:
    database:
        image: postgres:12.2
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: public

    backup:
        image: postgres-backup
        volumes:
            - ./backups:/backups
